### PR TITLE
feat: set up sendgrid mail integration

### PR DESCRIPTION
**Pull request by karrui**
allows users who do not have access to postman to still use sendgrid

docs are also up at https://github.com/opengovsg/starter-kit-docs/pull/17

### CODE REVIEW

**Review by lamkeewei — APPROVED** [review]
Didn't test out. But code lgtm!

**Comment by lamkeewei** [comment]
> Didn't test out. But code lgtm!

@karrui where did we restrict to open.gov.sg domains ah? Might need to loosen.

**Comment by karrui** [comment]
@lamkeewei 
> @karrui where did we restrict to open.gov.sg domains ah? Might need to loosen.

we actually didn't haha. Let me update the copy to just `Log in with your email`

**Comment by karrui** [comment]
Also proving Chromatic snapshots work since it should catch the new field title copy!!!

**Pull request merged**
